spring:
  application:
    name: challenge-java-developer

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
      doc-expansion: list
      tags-sorter: alpha
      operations-sorter: method
      try-it-out-enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:neurotechdb
    driver-class-name: org.h2.Driver
    username: admin
    password: neurotechdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
